# ATENÇÃO: Esse arquivo é para uso local apenas.
# O Render NÃO usa docker-compose.

version: '3.8'

services:
  web:
    build: .
    container_name: relatyze-api
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: relatyze-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kkkrsrsrs28?
      POSTGRES_DB: relatorios_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
