GOOGLE_CLIENT_ID = "1029730565033-8h5cnstnllrtgeoej1ghnuvrn8gic255.apps.googleusercontent.com"
GOOGLE_PROJECT_ID = "emerald-ivy-464517-m6"
GOOGLE_CLIENT_SECRET = "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"
GOOGLE_AUTH_URI = "https://accounts.google.com/o/oauth2/auth"
GOOGLE_TOKEN_URI = "https://oauth2.googleapis.com/token"
GOOGLE_CERT_URL = "https://www.googleapis.com/oauth2/v1/certs"
GOOGLE_REDIRECT_URI = "http://localhost:3000/oauth/callback"
GOOGLE_ORIGIN = "http://localhost:3000"
